### ISSUE TITLE
Setting ApiOperationBase<ANetApiRequest, ANetApiResponse>.RunEnvironment Error

### ISSUE THREAD

**Issue by totalpanic** [AuthorizeNet/sample-code-csharp#107]
Hi,

We have upgraded our project to .Net Core 3.1 and are now getting the below error when trying to set any of the ApiOperationBase values:
```

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'AuthorizeNet.Api.Controllers.Bases.ApiOperationBase`2' threw an exception.
  Source=AuthorizeNET
  StackTrace:
   at AuthorizeNet.Api.Controllers.Bases.ApiOperationBase`2.set_RunEnvironment(Environment value)
   at efs.portal.api.services.PaymentGateway.AuthNetGateway..ctor(IConfiguration config, IMapper mapper, ILoggerFactory loggerFactory) in D:\WORK\EFS\Code\efs-portal-api\Projects\efs-services\PaymentGateway\AuthNetGateway.cs:line 40

Inner Exception 1:
MissingMethodException: Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory Microsoft.Extensions.Logging.DebugLoggerFactoryExtensions.AddDebug(Microsoft.Extensions.Logging.ILoggerFactory, Microsoft.Extensions.Logging.LogLevel)'.
```
is this a compatibility issue with 3.1 or something different?

Thanks,
Gennadi

**Comment by totalpanic** [comment]
Please refer to same issue in code_beta project for the solution.
